### ISSUE TITLE
Add some basic scientific packages

### ISSUE THREAD

**Issue by lupinix** [fedora-python/fedora-kickstarts-python-classroom#1]
Thank you very much, this project looks very useful to me (I'm teaching Python at university sometimes). As Python is used in science more and more, I'd like to ask for some basic scientific packages (and the machine learning related scikit packages) in the new Lab, they are all general packages for scientific use, no specific ones like astropy stack (which I have in Fedora Astronomy for more specialized users):

- matplotlib including tk backend
- numpy
- pandas
- pillow
- scikit-image
- scikit-learn
- scipy
- statsmodels
- sympy

For scientific use, the Spyder IDE (python3-spyder for py3 support too) is commonly used, but this is more a "nice to have".

**Comment by hroncok** [comment]
Well with our Classroom lab, we intended to bring the Pythons and let users use pip to install stuff via virtualenvs https://developer.fedoraproject.org/tech/languages/python/python-installation.html

**Comment by lupinix** [comment]
I agree in general, but in case of some numerical packages it is not that reliable :( scikit-learn is a "famous" candidate for this. For my own usage I can just use Scientific or Astronomy of course, but for general promotion I think your project is the better one for python classes :)

**Comment by hroncok** [comment]
OK, we are  now trying to make this work and the deadline is coming. Once we have at least something in hand, we can discuss more about what to include. Keeping this open.

**Comment by hroncok** [comment]
This was fixed. https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/WTYPHMIU4WW4MFBVKWFAGKTD7XS6ZVXJ/
